//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiloTakipSistemi.Entity7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBolgeler
    {
        public int ID { get; set; }
        public string İl { get; set; }
        public string Bolge { get; set; }
    }
}
