//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiloTakipSistemi.Entity7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDetay
    {
        public int ID { get; set; }
        public string Plaka { get; set; }
        public string ReferansNo { get; set; }
        public string TMSOrderID { get; set; }
        public string Firma { get; set; }
        public string Proje { get; set; }
        public string HizmetTipi { get; set; }
        public string IstenilenAracTipi { get; set; }
        public string SiparisNumarasi { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<System.DateTime> YuklemeTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string NoktaSayisi { get; set; }
        public string YuklemeNoktasi { get; set; }
        public string YuklemeIli { get; set; }
        public string YuklemeIlcesi { get; set; }
        public string SiparisDurumu { get; set; }
        public string TeslimNoktasi { get; set; }
        public string TeslimIli { get; set; }
        public string TeslimIlcesi { get; set; }
        public string MusteriSiparisNo { get; set; }
        public string MusteriReferansNo { get; set; }
        public string Aciklama { get; set; }
        public string SiparisAcan { get; set; }
        public Nullable<System.DateTime> SiparisAcilisZamani { get; set; }
        public string PozisyonNo { get; set; }
        public string ToplamKg { get; set; }
        public Nullable<System.DateTime> TahminiVaris { get; set; }
        public string TahminiKm { get; set; }
        public Nullable<System.DateTime> Gerceklesen { get; set; }
        public Nullable<System.DateTime> YuklemeNoktasiVarısTarihi { get; set; }
        public Nullable<System.DateTime> YuklemeNoktasiCikisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimNoktasiCikisTarihi { get; set; }
    }
}
