//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiloTakipSistemi.Entity7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMesafe
    {
        public string YuklemeIl { get; set; }
        public string YuklemeIlce { get; set; }
        public string TahliyeIl { get; set; }
        public string TahliyeIlce { get; set; }
        public string ToplamMesafe { get; set; }
        public int ID { get; set; }
    }
}
