//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiloTakipSistemi.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiloTakipEntities5 : DbContext
    {
        public FiloTakipEntities5()
            : base("name=FiloTakipEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAraclar> TblAraclar { get; set; }
        public virtual DbSet<TblAracStatu> TblAracStatu { get; set; }
        public virtual DbSet<TblBolgeler> TblBolgeler { get; set; }
        public virtual DbSet<TblGiris> TblGiris { get; set; }
        public virtual DbSet<TblMesafe> TblMesafe { get; set; }
        public virtual DbSet<TblPlakaAtandi> TblPlakaAtandi { get; set; }
        public virtual DbSet<TblPlakaDurumları> TblPlakaDurumları { get; set; }
        public virtual DbSet<TblSebepler> TblSebepler { get; set; }
        public virtual DbSet<TblSiparisListesi> TblSiparisListesi { get; set; }
    }
}
