//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiloTakipSistemi.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAraclar
    {
        public int ID { get; set; }
        public string CekiciDorse { get; set; }
        public string SurucuIsim { get; set; }
        public Nullable<double> Telefon { get; set; }
        public Nullable<double> Tc { get; set; }
        public Nullable<double> SurucuDogumYil { get; set; }
        public string IkametAdresi { get; set; }
        public string CekiciRuhsatNo { get; set; }
        public string TedarikciIsim { get; set; }
        public string AracMarka { get; set; }
        public string AracModel { get; set; }
        public Nullable<System.DateTime> CekiciMuayene { get; set; }
        public Nullable<System.DateTime> DorseMuayene { get; set; }
        public Nullable<System.DateTime> TrafikSigorta { get; set; }
        public Nullable<double> AracYil { get; set; }
        public Nullable<double> DorseYil { get; set; }
        public string IsBasiKm { get; set; }
        public string Bolge { get; set; }
        public Nullable<System.DateTime> IsBasiTarih { get; set; }
        public string DorseTip { get; set; }
        public string Liftmaster { get; set; }
        public string SozlesmeDurumu { get; set; }
        public string Dingil { get; set; }
        public string GpsDurum { get; set; }
        public string HgsDurum { get; set; }
        public string TedarikciOzmalAracSigortaDurumu { get; set; }
        public string OdakK1 { get; set; }
        public string Status { get; set; }
    }
}
